SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

use `LHUB`;

insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Orin', 'Des Moines', 'IA', '50362', 'Draper', 'Gwenora', 'gdraper0@amazon.co.jp', '515-113-6777');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Warbler', 'Denver', 'CO', '80204', 'Northidge', 'Claiborn', 'cnorthidge1@ifeng.com', '303-825-2956');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Grayhawk', 'Topeka', 'KS', '66617', 'Wye', 'Derby', 'dwye2@wikimedia.org', '785-560-5689');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Lunder', 'White Plains', 'NY', '10633', 'Cholerton', 'Delia', 'dcholerton3@ibm.com', '914-352-7393');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Anderson', 'Salem', 'OR', '97312', 'McGilben', 'Bertrand', 'bmcgilben4@nps.gov', '971-571-9367');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Arapahoe', 'Oklahoma City', 'OK', '73142', 'Magson', 'Lindsay', 'lmagson5@archive.org', '405-844-4267');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Crowley', 'Houston', 'TX', '77299', 'Rathe', 'Donny', 'drathe6@hostgator.com', '713-514-2749');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Monterey', 'Philadelphia', 'PA', '19184', 'Driuzzi', 'Agneta', 'adriuzzi7@yelp.com', '215-944-9575');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Sloan', 'Omaha', 'NE', '68134', 'Machen', 'Morse', 'mmachen8@ucoz.ru', '402-626-4838');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Sachs', 'Lawrenceville', 'GA', '30045', 'Batteson', 'Marie', 'mbatteson9@pen.io', '404-334-3678');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Hagan', 'Berkeley', 'CA', '94705', 'Leverentz', 'Willy', 'wleverentza@tiny.cc', '510-210-4107');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Prentice', 'Paterson', 'NJ', '07505', 'Broadhurst', 'Tamar', 'tbroadhurstb@economist.com', '973-600-6597');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Cody', 'Dearborn', 'MI', '48126', 'McKag', 'Aggie', 'amckagc@jiathis.com', '313-659-0965');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Prentice', 'Chicago', 'IL', '60604', 'Petkovic', 'Isobel', 'ipetkovicd@youtube.com', '630-917-8601');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Shopko', 'Vancouver', 'WA', '98682', 'Jeger', 'Holly-anne', 'hjegere@xing.com', '360-349-1810');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Fuller', 'Cincinnati', 'OH', '45296', 'Pond', 'Shane', 'spondf@amazon.co.uk', '513-792-2288');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Kropf', 'San Jose', 'CA', '95160', 'Dupoy', 'Willard', 'wdupoyg@comsenz.com', '408-786-2769');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Lake View', 'Oklahoma City', 'OK', '73173', 'Ragdale', 'Blaine', 'bragdaleh@amazon.com', '405-269-2222');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Portage', 'Monticello', 'MN', '55585', 'MacCulloch', 'Lidia', 'lmaccullochi@time.com', '763-732-4943');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Chive', 'West Palm Beach', 'FL', '33411', 'Cyples', 'Opaline', 'ocyplesj@google.ca', '561-220-2776');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Magdeline', 'Nashville', 'TN', '37240', 'Lifton', 'Janeen', 'jliftonk@live.com', '615-703-1422');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Rockefeller', 'Sarasota', 'FL', '34238', 'Gladdish', 'Morty', 'mgladdishl@issuu.com', '941-267-5977');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Jackson', 'Nashville', 'TN', '37220', 'Guswell', 'Tanhya', 'tguswellm@slideshare.net', '615-287-2808');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Logan', 'Van Nuys', 'CA', '91406', 'Wilkison', 'Gilbert', 'gwilkisonn@columbia.edu', '805-459-6831');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('High Crossing', 'Jackson', 'MS', '39282', 'Tooher', 'Aurelia', 'atoohero@wufoo.com', '601-457-9585');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Blackbird', 'Columbia', 'SC', '29225', 'Mussettini', 'Merissa', 'mmussettinip@imgur.com', '803-352-4016');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Lien', 'Stamford', 'CT', '06922', 'Shimony', 'Corri', 'cshimonyq@buzzfeed.com', '203-170-3550');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Morning', 'Topeka', 'KS', '66606', 'Duxbury', 'Nelson', 'nduxburyr@wikipedia.org', '785-688-5606');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Dwight', 'Springfield', 'IL', '62718', 'Beaton', 'Eddi', 'ebeatons@github.io', '217-982-1157');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Hoffman', 'Tampa', 'FL', '33633', 'Keuneke', 'Davita', 'dkeuneket@creativecommons.org', '813-921-9053');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Ronald Regan', 'Fort Lauderdale', 'FL', '33320', 'Shipcott', 'Joane', 'jshipcottu@macromedia.com', '754-579-8896');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Anniversary', 'Spring', 'TX', '77386', 'De la Feld', 'Thomasina', 'tdelafeldv@jiathis.com', '832-730-5814');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Northport', 'Muncie', 'IN', '47306', 'Lomen', 'Vinnie', 'vlomenw@ftc.gov', '765-967-4240');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Melby', 'Savannah', 'GA', '31405', 'Coneau', 'Andrei', 'aconeaux@paypal.com', '912-216-3152');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Vahlen', 'Kansas City', 'MO', '64125', 'Crohan', 'Cecilla', 'ccrohany@tamu.edu', '816-796-4034');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Manufacturers', 'Birmingham', 'AL', '35285', 'Maylor', 'Jone', 'jmaylorz@gnu.org', '205-870-1262');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Delaware', 'Los Angeles', 'CA', '90045', 'Boman', 'Deanne', 'dboman10@prnewswire.com', '310-832-5859');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Lakeland', 'Louisville', 'KY', '40233', 'Huggill', 'Rey', 'rhuggill11@ted.com', '502-853-8184');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Portage', 'Washington', 'DC', '20057', 'Showte', 'Velvet', 'vshowte12@paypal.com', '202-233-3571');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Kinsman', 'Chicago', 'IL', '60669', 'Galley', 'Vaughn', 'vgalley13@elpais.com', '312-338-9515');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('7th', 'Seattle', 'WA', '98158', 'Soldi', 'Evaleen', 'esoldi14@sciencedirect.com', '425-998-4505');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Vidon', 'Augusta', 'GA', '30911', 'Eversley', 'Aloysia', 'aeversley15@shinystat.com', '706-125-0444');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Cody', 'Chicago', 'IL', '60697', 'Ogers', 'Keenan', 'kogers16@bandcamp.com', '312-659-3642');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Fairfield', 'Henderson', 'NV', '89074', 'Ciccottio', 'Padraig', 'pciccottio17@liveinternet.ru', '702-784-4988');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Aberg', 'Boston', 'MA', '02216', 'Chaundy', 'Ardine', 'achaundy18@behance.net', '617-679-1322');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Truax', 'Des Moines', 'IA', '50362', 'Cleevely', 'Conn', 'ccleevely19@techcrunch.com', '515-132-8312');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Charing Cross', 'Salt Lake City', 'UT', '84140', 'Gumery', 'Haslett', 'hgumery1a@flickr.com', '801-467-4919');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Westridge', 'Richmond', 'VA', '23208', 'Klimas', 'Dore', 'dklimas1b@over-blog.com', '804-333-2510');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Canary', 'Irvine', 'CA', '92717', 'Habbeshaw', 'Jessie', 'jhabbeshaw1c@psu.edu', '714-945-2464');
insert into client (street, city, state, zip, last_name, first_name, email, phone_number) values ('Melrose', 'New York City', 'NY', '10249', 'Massel', 'Umeko', 'umassel1d@t-online.de', '212-590-3986');
