SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

use `LHUB`;

INSERT INTO events (event_id, description, location, date_time) VALUES (1, "in-person meeting", "client's home", "2/3/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (2, "document signing", "meeting room 4", "2/2/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (3, "court appearance", "New York Supreme Court", "4/12/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (4, "in-person meeting", "office", "3/8/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (5, "court appearance", "New York County Courthouse", "3/29/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (6, "in-person meeting", "meeting room 2", "3/13/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (7, "document signing", "meeting room 5", "2/10/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (8, "in-person meeting", "office", "2/5/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (9, "court appearance", "New York Supreme Court", "3/18/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (10, "document signing", "meeting room 1", "3/8/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (11, "in-person meeting", "meeting room 4", "1/2/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (12, "court appearance", "Kings County Supreme Court", "2/22/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (13, "document signing", "meeting room 5", "1/25/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (14, "in-person meeting", "Cafe", "1/4/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (15, "court appearance", "Bronx County Hall of Justice", "4/9/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (16, "in-person meeting", "Cafe", "3/6/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (17, "document signing", "meeting room 3", "2/6/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (18, "in-person meeting", "Cafe", "3/23/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (19, "court appearance", "New York County Courthouse", "2/16/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (20, "document signing", "Cafe", "1/26/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (21, "in-person meeting", "office", "1/19/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (22, "court appearance", "Queens County Supreme Court", "3/22/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (23, "document signing", "meeting room 4", "1/29/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (24, "in-person meeting", "Cafe", "3/27/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (25, "court appearance", "Richmond County Supreme Court", "1/29/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (26, "in-person meeting", "meeting room 2", "3/28/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (27, "document signing", "meeting room 1", "1/14/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (28, "in-person meeting", "meeting room 3", "4/6/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (29, "court appearance", "New York Supreme Court", "2/3/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (30, "document signing", "Cafe", "3/18/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (31, "in-person meeting", "meeting room 4", "1/21/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (32, "court appearance", "New York County Courthouse", "3/3/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (33, "document signing", "office", "4/6/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (34, "in-person meeting", "meeting room 5", "1/21/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (35, "court appearance", "New York Supreme Court", "1/14/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (36, "document signing", "meeting room 3", "2/2/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (37, "in-person meeting", "meeting room 1", "1/6/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (38, "court appearance", "New York County Courthouse", "3/20/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (39, "document signing", "office", "2/16/2024");
INSERT INTO events (event_id, description, location, date_time) VALUES (40, "in-person meeting", "meeting room 2", "4/13/2024");
